apiVersion: apps/v1
kind: Deployment
metadata:
    name: nirg-secrets
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: nirg-secrets
  template:
    metadata:
      labels:
        name: nirg-secrets
    spec:
      containers:
      - name: nirg-secrets
        image: nirgeier/k8s-secrets-sample
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: LANGUAGE
          value: Hebrew
        - name: TOKEN
          value: Hard-To-Guess2